package org.lasalledebain.libris.util;

import java.util.Arrays;
import java.util.Iterator;
import java.util.Random;

public class Lorem implements Iterator<String[]> {
	public Lorem(int minSize, int maxSize, long seed) {
		gen = new Random(seed);
		this.minSize = minSize;
		this.maxSize = maxSize;
		cursor = 0;
	}

	/**
	 * @return the words
	 */
	public static String[] getWords() {
		return words;
	}

	public static final String words[] =
		{"Phasellus", "aliquet", "diam", "id", "accumsan", "ultrices", "est", "nulla",
				"suscipit", "dui", "sit", "amet", "condimentum", "augue", "neque", "luctus",
				"libero", "Etiam", "volutpat", "imperdiet", "tempus", "Ut", "laoreet", "leo",
				"nec", "maximus", "gravida", "Interdum", "et", "malesuada", "fames", "ac",
				"ante", "ipsum", "primis", "in", "faucibus", "In", "ante", "arcu", "vulputate",
				"sit", "amet", "magna", "id", "pulvinar", "suscipit", "est", "Donec",
				"fermentum", "purus", "in", "mauris", "egestas", "eleifend", "Pellentesque",
				"vitae", "arcu", "dapibus", "pharetra", "mauris", "nec", "efficitur", "odio",
				"Cras", "laoreet", "eros", "at", "sodales", "convallis", "Donec", "varius",
				"eleifend", "lectus", "vitae", "rhoncus", "nunc", "molestie", "a", "Sed",
				"ultrices", "finibus", "orci", "eget", "auctor", "Duis", "finibus", "ante",
				"nec", "ornare", "egestas", "Donec", "nec", "consequat", "mi", "Nunc", "eget",
				"rhoncus", "dui", "Vestibulum", "ac", "tortor", "rutrum", "mattis", "tellus",
				"vel", "eleifend", "sapien", "Proin", "bibendum", "ex", "id", "consequat",
				"gravida", "dui", "sem", "venenatis", "ipsum", "sit", "amet", "tincidunt",
				"lacus", "dolor", "sed", "massa", "Sed", "volutpat", "lorem", "eget", "nibh",
				"lacinia", "aliquet", "Donec", "pellentesque", "eleifend", "venenatis",
				"Phasellus", "dictum", "hendrerit", "eleifend", "Nunc", "neque", "nisl",
				"ornare", "id", "aliquam", "ac", "aliquam", "ut", "erat", "Vivamus", "cursus",
				"nisi", "vitae", "justo", "imperdiet", "lobortis", "Etiam", "egestas", "et",
				"eros", "vel", "pellentesque", "Donec", "gravida", "a", "nisl", "sed",
				"tristique", "Phasellus", "vitae", "risus", "risus", "Sed", "ac", "ligula",
				"ut", "enim", "luctus", "pellentesque", "Donec", "volutpat", "arcu", "nec",
				"lorem", "fermentum", "eleifend", "Pellentesque", "eros", "quam", "malesuada",
				"id", "lacus", "vel", "placerat", "tempor", "lorem", "Duis", "nec", "elit",
				"posuere", "consequat", "justo", "vel", "bibendum", "lorem", "Vestibulum",
				"lobortis", "odio", "in", "risus", "faucibus", "et", "commodo", "urna",
				"pulvinar", "Vivamus", "vitae", "rutrum", "velit", "Sed", "luctus", "nibh",
				"a", "finibus", "accumsan", "dolor", "ex", "sagittis", "erat", "id",
				"pellentesque", "tellus", "odio", "non", "ipsum", "Aenean", "euismod",
				"ultricies", "sem", "et", "egestas", "Sed", "laoreet", "sapien", "in",
				"sagittis", "posuere", "nunc", "arcu", "tempor", "orci", "in", "mollis",
				"elit", "velit", "nec", "purus", "Mauris", "eget", "turpis", "sit", "amet",
				"ante", "ultricies", "mattis", "ac", "interdum", "ante", "Nulla", "rutrum",
				"nisi", "laoreet", "erat", "tempus", "sed", "volutpat", "mi", "eleifend",
				"Quisque", "quis", "pellentesque", "sem", "Lorem", "ipsum", "dolor", "sit",
				"amet", "consectetur", "adipiscing", "elit", "Pellentesque", "ut", "interdum",
				"nulla", "Nunc", "nec", "ultricies", "eros", "Donec", "in", "lorem", "at",
				"mauris", "tempus", "lobortis", "sed", "ac", "eros", "Fusce", "ultrices",
				"hendrerit", "euismod", "Cras", "et", "posuere", "eros", "at", "molestie",
				"odio", "Mauris", "in", "congue", "dolor", "Phasellus", "facilisis", "massa",
				"et", "tortor", "facilisis", "vel", "consectetur", "turpis", "posuere",
				"Morbi", "sollicitudin", "metus", "eget", "purus", "tempor", "facilisis", "Ut",
				"sit", "amet", "orci", "eget", "risus", "congue", "laoreet", "Donec",
				"sodales", "felis", "nec", "convallis", "cursus", "Fusce", "scelerisque",
				"interdum", "sagittis", "Ut", "porttitor", "enim", "non", "justo", "posuere",
				"tristique", "Quisque", "diam", "libero", "eleifend", "eu", "pellentesque",
				"id", "ultricies", "ut", "dolor", "In", "hac", "habitasse", "platea",
				"dictumst", "Integer", "facilisis", "enim", "turpis", "et", "pellentesque",
				"erat", "ultricies", "ut", "In", "hac", "habitasse", "platea", "dictumst",
				"Sed", "pretium", "eleifend", "mi", "vel", "luctus", "massa", "ultricies",
				"id", "Morbi", "ultricies", "nunc", "urna", "sed", "sollicitudin", "nibh",
				"ornare", "sed", "Phasellus", "lacinia", "dolor", "vitae", "bibendum",
				"efficitur", "Nullam", "hendrerit", "gravida", "lacus", "eu", "commodo", "Sed",
				"vulputate", "luctus", "massa", "sit", "amet", "fringilla", "Nullam",
				"porttitor", "nisi", "eu", "magna", "dignissim", "aliquam", "vel", "laoreet",
				"turpis", "Proin", "sem", "urna", "suscipit", "ac", "dui", "fringilla",
				"porta", "egestas", "nunc", "Curabitur", "congue", "elit", "et", "diam",
				"sollicitudin", "auctor", "Mauris", "malesuada", "leo", "quis", "odio",
				"maximus", "imperdiet", "Class", "aptent", "taciti", "sociosqu", "ad",
				"litora", "torquent", "per", "conubia", "nostra", "per", "inceptos",
				"himenaeos", "Nam", "libero", "nisi", "suscipit", "eu", "euismod", "a",
				"pharetra", "non", "orci", "Nullam", "eget", "ligula", "metus", "Duis", "dui",
				"mauris", "pellentesque", "id", "sapien", "at", "accumsan", "bibendum",
				"felis", "Sed", "et", "leo", "nunc", "Curabitur", "vehicula", "commodo",
				"ornare", "Ut", "sed", "fermentum", "tortor", "in", "facilisis", "erat",
				"Curabitur", "eu", "libero", "eu", "ipsum", "molestie", "euismod", "sed", "et",
				"quam", "Pellentesque", "sodales", "maximus", "ex", "non", "tristique", "dui",
				"lobortis", "at", "Aenean", "faucibus", "tellus", "eu", "est", "laoreet",
				"iaculis", "Aliquam", "finibus", "sollicitudin", "risus", "Integer",
				"tincidunt", "ex", "id", "tellus", "placerat", "aliquam", "Sed", "pretium",
				"semper", "nibh", "sed", "volutpat", "dui", "euismod", "sed", "Nam", "quis",
				"semper", "sapien", "Fusce", "imperdiet", "porttitor", "consectetur", "Sed",
				"sollicitudin", "magna", "ullamcorper", "dolor", "congue", "sit", "amet",
				"rhoncus", "nulla", "placerat", "Donec", "sit", "amet", "arcu", "id", "ligula",
				"vehicula", "sagittis", "vel", "vitae", "ex", "Mauris", "ac", "vulputate",
				"nibh", "Etiam", "massa", "dolor", "faucibus", "eu", "massa", "ac",
				"convallis", "volutpat", "mi", "Mauris", "lorem", "elit", "accumsan", "ac",
				"facilisis", "eu", "facilisis", "eget", "erat", "Ut", "vitae", "dui", "eget",
				"sem", "molestie", "vehicula", "ac", "id", "sem", "Aliquam", "egestas", "nunc",
				"erat", "id", "finibus", "felis", "blandit", "ut", "Integer", "libero", "nibh",
				"dapibus", "ac", "ante", "vitae", "imperdiet", "convallis", "orci", "Etiam",
				"commodo", "neque", "ac", "lacus", "posuere", "maximus", "Suspendisse",
				"sodales", "iaculis", "ipsum", "vel", "suscipit", "Nam", "dictum", "lorem",
				"eget", "maximus", "egestas", "quam", "nibh", "volutpat", "odio", "nec",
				"tincidunt", "dolor", "libero", "ut", "lectus", "Nullam", "placerat", "lectus",
				"id", "vestibulum", "convallis", "risus", "massa", "accumsan", "tortor", "eu",
				"dictum", "sapien", "libero", "in", "ex", "Vestibulum", "dictum", "lacinia",
				"interdum", "Donec", "eleifend", "suscipit", "ligula", "ac", "bibendum",
				"quam", "venenatis", "at", "Duis", "neque", "lorem", "iaculis", "ultrices",
				"consequat", "in", "viverra", "sed", "purus", "In", "congue", "ligula", "non",
				"placerat", "laoreet", "Cras", "augue", "leo", "pulvinar", "et", "turpis",
				"id", "ultrices", "gravida", "libero", "Nam", "eu", "arcu", "ligula", "Nullam",
				"sed", "tincidunt", "massa", "Morbi", "sit", "amet", "eros", "a", "felis",
				"lacinia", "lacinia", "a", "nec", "nibh", "Praesent", "egestas", "vestibulum",
				"orci", "Phasellus", "ut", "vulputate", "tortor", "ut", "fermentum", "ligula",
				"Aenean", "porttitor", "nibh", "sapien", "at", "dictum", "magna", "ultrices",
				"vel", "Suspendisse", "auctor", "tortor", "magna", "et", "vestibulum", "nisi",
				"venenatis", "et", "Cras", "molestie", "consectetur", "velit", "at",
				"faucibus", "Vivamus", "mi", "neque", "vulputate", "eget", "metus", "at",
				"ornare", "semper", "turpis", "Nulla", "cursus", "enim", "a", "ultrices",
				"luctus", "lectus", "odio", "convallis", "elit", "eu", "consequat", "felis",
				"neque", "pretium", "arcu", "Proin", "dapibus", "vitae", "leo", "et", "ornare",
				"Morbi", "neque", "lectus", "rhoncus", "sed", "eleifend", "non", "malesuada",
				"ac", "dui", "Pellentesque", "dictum", "at", "nisl", "sit", "amet",
				"tincidunt", "Vestibulum", "leo", "sapien", "porttitor", "in", "pharetra",
				"et", "lobortis", "et", "lorem", "Donec", "ut", "orci", "non", "lectus",
				"mollis", "pharetra", "Nulla", "dolor", "felis", "mollis", "sit", "amet",
				"quam", "non", "euismod", "lobortis", "ex", "Integer", "quis", "nisl", "eget",
				"quam", "ornare", "bibendum", "vitae", "a", "velit", "In", "eleifend",
				"iaculis", "felis", "sit", "amet", "ullamcorper", "Phasellus", "tristique",
				"rutrum", "interdum", "In", "blandit", "felis", "in", "lobortis", "venenatis",
				"Mauris", "pulvinar", "auctor", "dui", "quis", "euismod", "Integer", "eget",
				"facilisis", "mi", "ut", "fringilla", "erat", "Aenean", "sit", "amet", "quam",
				"nec", "ante", "sollicitudin", "tincidunt", "in", "facilisis", "ex", "Quisque",
				"lorem", "turpis", "convallis", "et", "egestas", "sit", "amet", "tempus", "a",
				"sem", "Aenean", "bibendum", "lacinia", "efficitur", "Quisque", "in",
				"feugiat", "augue", "et", "viverra", "erat", "Lorem", "ipsum", "dolor", "sit",
				"amet", "consectetur", "adipiscing", "elit", "Sed", "gravida", "lorem", "nec",
				"lorem", "maximus", "pellentesque", "Nulla", "ac", "mi", "sed", "purus",
				"vestibulum", "finibus", "Vivamus", "dictum", "a", "felis", "ut", "vehicula",
				"Donec", "viverra", "congue", "lorem", "ut", "iaculis", "Proin", "ac",
				"rhoncus", "odio", "Donec", "pretium", "gravida", "nisl", "id", "pulvinar",
				"Duis", "et", "leo", "nec", "diam", "consequat", "posuere", "Duis",
				"tincidunt", "rutrum", "libero", "sed", "condimentum", "Cras", "sit", "amet",
				"massa", "at", "nunc", "iaculis", "viverra"};
	int minSize;
	int maxSize;
	int cursor;
	Random gen;

	@Override
	public boolean hasNext() {
		return (cursor + minSize) < words.length;
	}

	@Override
	public String[] next() {
		int len = gen.nextInt(maxSize - minSize + 1) + minSize;
		int to = Math.min(cursor + len, words.length - 1);
		String[] result = Arrays.copyOfRange(words, cursor, to);
		cursor += len;
		return result;
	}
	
	public static String journalWords[] = {"abandon", "abandoned", "abandoning", "abort", "aborted", "aborts", "about",
			"above", "absence", "absolute", "abstract", "abstraction", "abstractions",
			"academic", "accept", "acceptable", "accepted", "access", "accessed",
			"accesses", "accessible", "accessing", "accomplished", "according", "account",
			"achieve", "acm", "acquire", "acquired", "across", "action", "activation",
			"actual", "actually", "add", "added", "addition", "additional", "address",
			"addressed", "addresses", "adds", "adequately", "adjacent", "adjust",
			"adopted", "adopting", "advantage", "affects", "after", "again", "against",
			"agreed", "al", "alert", "algol", "aliasing", "all", "alleviated", "allocate",
			"allocated", "allocates", "allocating", "allocation", "allocator", "allow",
			"allowed", "allows", "alone", "already", "also", "alternative", "alternatives",
			"although", "alto", "always", "am", "american", "among", "amount", "an",
			"analysis", "and", "annoying", "anomalies", "another", "anticipated", "any",
			"anyway", "appear", "appeared", "appears", "application", "applications",
			"applied", "approach", "appropriate", "appropriately", "april", "arbitrarily",
			"arbitrary", "architecture", "are", "area", "areas", "argument", "arguments",
			"arise", "arises", "around", "arrange", "arrangement", "array", "arrays",
			"arrival", "arrived", "articulated", "as", "aside", "aspects", "assigned",
			"assignment", "associate", "associated", "association", "assume", "assumed",
			"assuming", "asymmetry", "asynchronous", "asynchronously", "at", "atomic",
			"atomically", "attached", "attempt", "attempts", "attention", "attitude",
			"attract", "attractive", "aug", "australian", "automatically", "autonomous",
			"available", "availablestorage", "avoid", "avoided", "avoids", "await",
			"awaken", "awakened", "away", "awkward", "back", "background", "balance",
			"based", "basic", "basis", "be", "because", "becauseofthe", "become",
			"becomes", "been", "before", "began", "begin", "beginning", "behaves",
			"behind", "being", "belong", "belongs", "below", "best", "better", "between",
			"beyond", "binary", "birth", "blame", "block", "blocks", "body", "boggs",
			"both", "bottleneck", "boundaries", "boundary", "branch", "break", "bredt",
			"briefly", "brinch", "bring", "broadcast", "broadcasts", "buffer", "buffers",
			"bug", "bugs", "building", "builds", "built", "burden", "business", "but",
			"butler", "by", "byte", "bytes", "c", "ca", "calendar", "calif", "call",
			"called", "caller", "calling", "calls", "can", "cannot", "care", "careful",
			"carefully", "carrier", "carries", "case", "cases", "cast", "casting", "casts",
			"categories", "cause", "caused", "causes", "cell", "cells", "center",
			"certain", "certainly", "chance", "change", "changed", "changes", "changing",
			"chaos", "characteristic", "characteristics", "cheap", "check", "checking",
			"checks", "choice", "choose", "chores", "chose", "chosen", "chunk", "circuit",
			"circular", "class", "classes", "clause", "clean", "cleanliness", "cleanup",
			"clearly", "client", "closely", "code", "coding", "collect", "collection",
			"come", "comfort", "comm", "commands", "commercial", "commits", "common",
			"communicate", "communicating", "communication", "communications", "compact",
			"compare", "compared", "competitive", "compile", "compiler", "complement",
			"complete", "completed", "completely", "completion", "complex", "complexity",
			"complicated", "complication", "component", "computation", "computations",
			"compute", "computer", "computing", "concept", "concern", "conclude",
			"conclusion", "concurrency", "concurrent", "concurrently", "condition",
			"conditions", "conf", "confidence", "configuration", "conflict", "confusion",
			"connected", "connection", "conscientious", "consequence", "consider",
			"considerable", "considerably", "considered", "consistent", "consisting",
			"consists", "constellation", "constitute", "constraints", "construct",
			"constructed", "construction", "constructor", "constructs", "consult",
			"consulting", "consumer", "contain", "containers", "containing", "contains",
			"contents", "context", "contexts", "continue", "continued", "continues",
			"contrary", "contributed", "contributes", "control", "convenient",
			"conveniently", "conventional", "converse", "conversely", "convincing",
			"cooperative", "cooperatively", "coordinate", "copies", "copy", "copying",
			"copyright", "correct", "correctness", "corresponding", "cost", "costs",
			"could", "coupled", "course", "covering", "covers", "cr", "create", "created",
			"creating", "creation", "creator", "critical", "crowdlarger", "crucial", "csl",
			"cumbersome", "current", "currently", "currentpage", "cyclic", "danger",
			"dangling", "data", "database", "databases", "datachanges", "date", "david",
			"deadlock", "deadlocks", "deal", "dealt", "death", "debugger", "dec",
			"decentralized", "decided", "decision", "decisions", "declaration", "decouple",
			"dedicated", "deficiency", "define", "defined", "defines", "defining",
			"definition", "delay", "delayed", "delete", "deletion", "deletions",
			"delicate", "delineate", "depended", "dependencies", "depending", "depends",
			"describe", "described", "describing", "description", "design", "designed",
			"designing", "desirable", "destroy", "destroyed", "destroying", "destruction",
			"detach", "detached", "detaches", "detailed", "details", "detect", "deter",
			"determine", "determined", "determines", "determining", "development",
			"device", "devices", "devise", "did", "differ", "differences", "different",
			"differently", "differs", "difficulties", "dijkstra", "direct", "directly",
			"disabled", "disappears", "discipline", "discovered", "discretion", "discuss",
			"discussed", "discusses", "discussion", "disk", "dispatcher", "dispatches",
			"dispatching", "display", "disruption", "distinct", "distinguished",
			"distributed", "division", "do", "does", "doing", "done", "down", "dozen",
			"drastically", "driver", "drivers", "duality", "duals", "due", "duplicating",
			"dures", "during", "dying", "dynamic", "dynamically", "each", "earlier",
			"early", "easier", "easily", "easy", "economies", "economy", "effect",
			"effectively", "efficiency", "efficient", "efficiently", "either",
			"elaboration", "element", "eligible", "eliminates", "embed", "embedded",
			"emits", "encapsulated", "enclosing", "encountered", "end", "endloop", "ends",
			"enforced", "enforcement", "engineering", "enough", "ensures", "enter",
			"enters", "entire", "entirely", "entries", "entry", "environment", "equally",
			"equivalent", "error", "errors", "especially", "essential", "essentially",
			"establish", "established", "establishes", "et", "etc", "ethernet",
			"evaluation", "even", "event", "events", "eventually", "ever", "every",
			"exact", "exactly", "examining", "example", "examples", "except", "exception",
			"exceptional", "exceptions", "exchanging", "exclusion", "execute", "executes",
			"executing", "execution", "exercise", "exert", "existence", "existing",
			"exists", "exit", "expand", "expectation", "expecting", "experience",
			"experienced", "experimental", "expire", "expired", "explicit", "explicitly",
			"exploiting", "express", "expressed", "expression", "extensive", "extent",
			"external", "extra", "extremely", "facilities", "facility", "fact", "fails",
			"faire", "fairly", "fall", "false", "familiar", "family", "far", "fast",
			"faster", "fault", "faults", "fdoo", "feasible", "feature", "features", "feb",
			"fee", "feel", "felt", "few", "fifo", "figure", "figures", "file", "filedata",
			"files", "filesuite", "filesuites", "finally", "find", "finds", "finer",
			"finish", "first", "fit", "fitting", "fixed", "flagged", "flexibility", "fme",
			"followed", "following", "for", "forbids", "forced", "forcing", "fork",
			"forked", "forking", "forks", "form", "forth", "forwarder", "forwarding",
			"forwards", "found", "four", "fourth", "fraction", "frame", "frames",
			"framework", "france", "francisco", "free", "freedom", "freeing", "frequency",
			"frequently", "from", "ftxed", "fully", "function", "functions", "fundamental",
			"further", "furthermore", "fuss", "future", "gateway", "gateways", "general",
			"generality", "generally", "generated", "generates", "generator", "gently",
			"get", "gifford", "give", "given", "gives", "giving", "global", "go", "goals",
			"goes", "going", "good", "grain", "granted", "group", "grove", "grows",
			"guarantee", "guarantees", "had", "hall", "hand", "handle", "handled",
			"handler", "handlers", "handles", "handling", "hansen", "happen", "happens",
			"hard", "hardware", "has", "have", "having", "head", "heap", "heavily",
			"heavy", "held", "help", "hence", "here", "hierarchical", "hierarchy", "high",
			"higher", "highest", "hint", "his", "hoare", "hold", "holds", "hope",
			"hopelessly", "housekeeping", "how", "howard", "however", "hundred", "idea",
			"identical", "identity", "ieee", "if", "ignore", "illusion", "illustrates",
			"immediately", "implement", "implementation", "implemented", "implementing",
			"implements", "implicit", "implicitly", "implied", "implies", "important",
			"impose", "imposes", "in", "inaccessible", "includes", "including", "increase",
			"increased", "increases", "indeed", "independent", "independently",
			"indicated", "indication", "indirection", "individual", "information",
			"infrequent", "inherent", "initialization", "initiate", "initiated", "input",
			"inquiry", "insert", "insertion", "insertions", "inside", "insist", "inst",
			"instance", "instances", "instead", "instruction", "instructions", "insured",
			"int", "integer", "integrated", "integrating", "integration", "intended",
			"intends", "intent", "inter", "interact", "interaction", "interactions",
			"interest", "interesting", "interface", "interfaces", "internal",
			"internetwork", "interprocess", "interrogating", "interrupt", "interrupts",
			"interval", "intervals", "into", "intolerable", "intrinsic", "introduce",
			"introduced", "introducing", "introduction", "invariant", "invention",
			"invoked", "invoking", "involve", "involved", "involves", "iria", "is",
			"israel", "issue", "issues", "it", "item", "iteratively", "its", "itself",
			"jan", "join", "joining", "joins", "jointly", "july", "june", "just",
			"justifies", "keedy", "keeping", "keeps", "kept", "key", "keyboard", "kind",
			"kinds", "know", "known", "l", "labor", "lack", "lackluster", "laissez",
			"lampson", "language", "languages", "large", "largely", "larger", "last",
			"later", "latest", "latter", "lauer", "layering", "lead", "leads", "least",
			"leaves", "leaving", "lecture", "left", "legitimate", "less", "let", "level",
			"levels", "lexical", "life", "like", "likely", "likes", "limited", "limiting",
			"line", "lines", "linked", "linking", "list", "listed", "lister", "lists",
			"literature", "little", "lo", "loads", "local", "localized", "locate",
			"location", "lock", "locked", "locks", "logic", "logically", "long", "longer",
			"looked", "lost", "low", "lower", "lowest", "m", "mac", "machine", "machinery",
			"machines", "made", "main", "mainframe", "maintained", "maintains", "make",
			"makes", "making", "management", "manager", "manipulations", "manner",
			"manual", "many", "mapping", "marking", "marks", "match", "material",
			"maximum", "may", "maybury", "maynard", "meaning", "meaningful", "means",
			"measuring", "mechanism", "mechanisms", "memory", "mental", "mesa", "message",
			"messages", "met", "metcalfe", "method", "microcode", "microcoded",
			"microsecond", "might", "mild", "mined", "minimal", "minimize", "minimum",
			"mip", "missing", "mit", "mitchell", "models", "moderate", "modern", "modest",
			"modula", "modular", "modularity", "module", "modules", "monitor", "monitored",
			"monitorentry", "monitoring", "monitors", "more", "moreavailable", "most",
			"motivated", "moved", "much", "multi", "multiple", "multiplexed",
			"multiprogramming", "must", "mutual", "mutually", "naive", "naked", "names",
			"nat", "national", "natural", "naturally", "nearly", "necessary", "need",
			"needed", "needham", "needs", "neither", "nested", "network", "networks",
			"never", "nevertheless", "new", "newly", "next", "no", "non", "none",
			"nonetheless", "nontrivial", "nor", "normal", "normally", "not", "notable",
			"note", "notes", "nothing", "notice", "noticed", "notices", "notification",
			"notified", "notifies", "notify", "nov", "november", "now", "number",
			"numbers", "object", "objected", "objects", "observed", "obtained",
			"obtaining", "occupies", "occupy", "occur", "occurred", "occurring", "occurs",
			"ocr", "oct", "of", "offer", "offered", "office", "often", "ok", "old", "on",
			"one", "only", "operands", "operating", "operation", "operational",
			"operations", "opportunities", "or", "order", "ordered", "ordering", "orderly",
			"ordinary", "organizing", "original", "other", "others", "otherwise", "our",
			"ours", "out", "output", "outside", "over", "overhead", "own", "p", "pacific",
			"package", "packet", "packets", "page", "pages", "paid", "pair", "pairwise",
			"palo", "paper", "papers", "paradigm", "parallelism", "parameter",
			"parameters", "part", "partial", "particular", "particularly", "parts",
			"pascal", "pass", "passed", "passing", "path", "paths", "pattern", "patterns",
			"per", "percent", "percentage", "perfectly", "perform", "performance",
			"performs", "periodically", "permission", "personal", "phrases", "pi", "pick",
			"pilot", "pl", "place", "placement", "plus", "pn", "pnew", "point", "pointed",
			"pointer", "pointers", "pointing", "pointless", "points", "pold", "policies",
			"poorly", "popular", "portion", "possessed", "possibilities", "possibility",
			"possible", "potential", "potentially", "power", "pp", "practical", "practice",
			"precedes", "precise", "predicate", "preempted", "preemption", "preemptions",
			"preemptive", "prentice", "prepared", "preparing", "preplan", "present",
			"presented", "press", "presumably", "prevent", "previously", "primarily",
			"primary", "prime", "primitive", "primitives", "principles", "printer",
			"prior", "priorities", "priority", "private", "problem", "problems", "proce",
			"procedure", "procedures", "proceed", "process", "processed", "processes",
			"processing", "processor", "processors", "processstate", "processstates",
			"prod", "produce", "producer", "produces", "program", "programmer",
			"programming", "programs", "proof", "proper", "properly", "properties",
			"proposal", "proposals", "protect", "protected", "protection", "proved",
			"provide", "provided", "provides", "providing", "provision", "provisions",
			"prqlwru", "pseudo", "public", "publication", "published", "pup", "purpose",
			"purposes", "put", "queue", "queueing", "queues", "quick", "quite", "quorum",
			"race", "races", "raised", "random", "range", "ranging", "rapid", "rapidly",
			"rarely", "rather", "reached", "reacquire", "reacquired", "read", "reader",
			"readline", "ready", "real", "realistic", "reason", "reasonable", "reasonably",
			"reasons", "rebirth", "received", "recent", "recognizes", "recommend",
			"recommended", "record", "recording", "records", "recovery", "recursive",
			"redell", "reduces", "reenters", "reevaluate", "reference", "references",
			"refers", "refined", "reflects", "regard", "regarded", "regardless", "regimes",
			"rejected", "related", "relationship", "relative", "relatively", "release",
			"released", "releases", "releasing", "reliable", "remain", "remains", "remark",
			"remarkably", "remote", "removal", "rendezvous", "replacing", "replenished",
			"replicated", "reply", "report", "reported", "reports", "repre",
			"representative", "representatives", "represented", "representing",
			"represents", "reprinted", "republish", "request", "requesting", "require",
			"required", "requirements", "requires", "research", "resemble", "reserve",
			"reside", "resident", "resolve", "resolved", "resource", "resources",
			"respectively", "respond", "response", "responsible", "restore", "restored",
			"restoring", "restricting", "restriction", "restrictions", "restricts",
			"result", "resultant", "resulted", "resulting", "results", "resume", "resumes",
			"retrieve", "retrieves", "retry", "return", "returned", "returning", "returns",
			"review", "revised", "right", "rocquencourt", "root", "roughly", "router",
			"routine", "routines", "routing", "rule", "rules", "run", "runaway", "running",
			"runs", "runtime", "rupt", "s", "safe", "safety", "said", "saltzer", "same",
			"san", "satterthwaite", "saving", "saxena", "say", "scanning", "scans",
			"scheduled", "scheduler", "scheduling", "scheme", "schemes", "science",
			"scope", "second", "secondary", "section", "sections", "see", "seemed", "seen",
			"seizing", "semantics", "semaphore", "semaphores", "send", "sends",
			"sentatives", "separate", "separating", "september", "sequence", "sequential",
			"sequentially", "serializing", "serious", "serve", "serves", "serviced", "set",
			"setting", "settling", "several", "share", "shared", "sharing", "short",
			"should", "shown", "signaled", "signaler", "signaling", "signals",
			"significantly", "sigplan", "similar", "simple", "simpler", "simplest",
			"simplifies", "simply", "simulating", "simultaneously", "since", "single",
			"situation", "situations", "size", "sizes", "slicing", "slightly", "slower",
			"sluggish", "small", "so", "socket", "software", "solution", "solutions",
			"solve", "solved", "solves", "some", "somehow", "sometimes", "somewhat",
			"somewhere", "soon", "sorted", "sound", "source", "space", "special",
			"specific", "specification", "specified", "specify", "speed", "speeds",
			"split", "springer", "stable", "stack", "standard", "standards", "start",
			"starvation", "state", "statement", "statements", "states", "static", "status",
			"still", "stop", "storage", "storageallocator", "store", "stored",
			"straightforward", "strategies", "strict", "strike", "strong", "stronger",
			"structure", "structured", "structures", "structuring", "sturgis", "style",
			"subject", "substantial", "substantially", "subtle", "subverted", "succeeded",
			"successful", "such", "sufficient", "sufficiently", "sugar", "sugared",
			"suggest", "suicide", "suitable", "suite", "suites", "sum", "summarize",
			"summarizes", "summary", "supplied", "supply", "supplying", "support",
			"supports", "suppose", "surfhvv", "surgery", "survey", "swap", "swappable",
			"swapping", "sweet", "switch", "switches", "switching", "symposium",
			"synchronization", "synchronize", "synchronized", "synchronizers",
			"synchronizes", "synchronizing", "syntactic", "system", "systems", "table",
			"tail", "take", "taken", "takes", "taking", "tape", "task", "techniques",
			"temporarily", "tend", "tends", "terminal", "terminate", "terminates",
			"testing", "tests", "text", "textually", "than", "that", "the", "their",
			"them", "themselves", "then", "there", "therefore", "these", "they", "think",
			"third", "this", "those", "though", "thought", "three", "through",
			"throughput", "thus", "tick", "ticks", "tightly", "time", "timeout",
			"timeouts", "times", "timesharing", "timing", "title", "to", "together", "too",
			"tool", "top", "total", "totally", "tr", "track", "traffic", "trans",
			"transaction", "transactional", "transactions", "transfer", "transfers",
			"transformation", "transmission", "transmit", "transmitted", "trap", "treated",
			"treatment", "treats", "tricky", "tries", "trouble", "true", "truth", "trying  commonpre",
			"turn", "turned", "turning", "twice", "two", "type", "types", "typical",
			"typically", "typing", "uhwxuq", "unable", "unacceptable", "unavailable",
			"unbounded", "unchanged", "under", "underlying", "understand",
			"understandable", "understanding", "unfairness", "unfortunately", "unifies",
			"unit", "unless", "unlocked", "unnecessary", "unreasonable", "unreferenced",
			"unrelated", "until", "unused", "unwind", "unwinds", "up", "update", "updated",
			"updates", "updating", "upheaval", "upon", "us", "usage", "use", "used",
			"useful", "usefulness", "user", "users", "uses", "using", "usual", "usually",
			"utility", "validity", "value", "vanished", "variable", "variables", "variety",
			"various", "vary", "varying", "vector", "vehicle", "verification", "version",
			"very", "via", "view", "views", "violet", "virtual", "volatile", "volume",
			"voluntarily", "voluntary", "voting", "wait", "waiter", "waiters", "waiting",
			"waits", "wake", "wakeup", "wakeups", "waking", "want", "wanted", "wants",
			"was", "way", "ways", "we", "weighted", "well", "were", "what", "when",
			"whenever", "where", "whether", "which", "while", "who", "whose", "why",
			"wide", "will", "willing", "wirth", "wish", "wishing", "with", "within",
			"without", "word", "words", "work", "worked", "workshop", "worst", "would",
			"write", "writing", "written", "x", "xerox", "yet", "yield", "yielded",
			"yielding", "york"};

	public static String fields[] =
		{"academic accept acceptable accepted access accessed",
				"accesses accessible accessing accomplished according account",
				"achieve acm acquire acquired across action activation",
				"actual actually add added addition additional address",
				"addressed addresses adds adequately adjacent adjust",
				"adopted adopting advantage affects after again against",
				"agreed al alert algol aliasing all alleviated allocate",
				"allocated allocates allocating allocation allocator allow",
				"allowed allows alone already also alternative alternatives",
				"although alto always am american among amount an",
				"analysis and annoying anomalies another anticipated any",
				"anyway appear appeared appears application applications",
				"applied approach appropriate appropriately april arbitrarily commonprefix",
				"arbitrary architecture are area areas argument arguments",
				"arise arises around arrange arrangement array arrays",
				"arrival arrived articulated as aside aspects assigned",
				"assignment associate associated association assume assumed",
				"assuming asymmetry asynchronous asynchronously at atomic",
				"atomically attached attempt attempts attention attitude",
				"attract attractive aug australian automatically autonomous",
				"available availablestorage avoid avoided avoids await",
				"awaken awakened away awkward back background balance",
				"based basic basis be because becauseofthe become",
				"becomes been before began begin beginning behaves",
				"behind being belong belongs below best better between",
				"beyond binary birth blame block blocks body boggs",
				"both bottleneck boundaries boundary branch break bredt",
				"briefly brinch bring broadcast broadcasts buffer buffers",
				"bug bugs building builds built burden business but",
				"butler by byte bytes ca calendar calif call",
				"called caller calling calls can cannot care careful",
				"carefully carrier carries case cases cast casting casts",
				"categories cause caused causes cell cells center",
				"certain certainly chance change changed changes changing",
				"chaos characteristic characteristics cheap check checking",
				"checks choice choose chores chose chosen chunk circuit",
				"circular class classes clause clean cleanliness cleanup",
				"clearly client closely code coding collect collection",
				"come comfort comm commands commercial commits common",
				"communicate communicating communication communications compact",
				"compare compared competitive compile compiler complement",
				"complete completed completely completion complex complexity",
				"complicated complication component computation computations",
				"compute computer computing concept concern conclude termone",
				"conclusion concurrency concurrent concurrently condition",
				"conditions conf confidence configuration conflict confusion",
				"connected connection conscientious consequence consider",
				"considerable considerably considered consistent consisting",
				"consists constellation constitute constraints construct",
				"constructed construction constructor constructs consult",
				"consulting consumer contain containers containing contains",
				"contents context contexts continue continued continues",
				"contrary contributed contributes control convenient",
				"conveniently conventional converse conversely convincing",
				"cooperative cooperatively coordinate copies copy copying",
				"copyright correct correctness corresponding cost costs",
				"could coupled course covering covers cr create created",
				"creating creation creator critical crowdlarger crucial csl",
				"cumbersome current currently currentpage cyclic danger",
				"dangling data database databases datachanges date david",
				"deadlock deadlocks deal dealt death debugger dec",
				"decentralized decided decision decisions declaration decouple",
				"dedicated deficiency define defined defines defining",
				"definition delay delayed delete deletion deletions",
				"delicate delineate depended dependencies depending depends",
				"describe described describing description design designed",
				"designing desirable destroy destroyed destroying destruction",
				"detach detached detaches detailed details detect deter",
				"determine determined determines determining development",
				"device devices devise did differ differences different",
				"differently differs difficulties dijkstra direct directly",
				"disabled disappears discipline discovered discretion discuss",
				"discussed discusses discussion disk dispatcher dispatches",
				"dispatching display disruption distinct distinguished",
				"distributed division do does doing done down dozen",
				"drastically driver drivers duality duals due duplicating",
				"dures during dying dynamic dynamically each earlier",
				"early easier easily easy economies economy effect",
				"effectively efficiency efficient efficiently either",
				"elaboration element eligible eliminates embed embedded",
				"emits encapsulated enclosing encountered end endloop ends",
				"enforced enforcement engineering enough ensures enter",
				"enters entire entirely entries entry environment equally",
				"equivalent error errors especially essential essentially",
				"establish established establishes et etc ethernet",
				"evaluation even event events eventually ever every",
				"exact exactly examining example examples except exception",
				"exceptional exceptions exchanging exclusion execute executes",
				"executing execution exercise exert existence existing termone termtwo",
				"exists exit expand expectation expecting experience",
				"experienced experimental expire expired explicit explicitly",
				"exploiting express expressed expression extensive extent",
				"external extra extremely facilities facility fact fails",
				"faire fairly fall false familiar family far fast",
				"faster fault faults fdoo feasible feature features feb",
				"fee feel felt few fifo figure figures file filedata",
				"files filesuite filesuites finally find finds finer",
				"finish first fit fitting fixed flagged flexibility fme",
				"followed following for forbids forced forcing fork",
				"forked forking forks form forth forwarder forwarding",
				"forwards found four fourth fraction frame frames",
				"framework france francisco free freedom freeing frequency",
				"frequently from ftxed fully function functions fundamental",
				"further furthermore fuss future gateway gateways general termone termtwo termthree",
				"generality generally generated generates generator gently",
				"get gifford give given gives giving global go goals",
				"goes going good grain granted group grove grows",
				"guarantee guarantees had hall hand handle handled",
				"handler handlers handles handling hansen happen happens",
				"hard hardware has have having head heap heavily",
				"heavy held help hence here hierarchical hierarchy high",
				"higher highest hint his hoare hold holds hope",
				"hopelessly housekeeping how howard however hundred idea",
				"identical identity ieee if ignore illusion illustrates",
				"immediately implement implementation implemented implementing termone termthree",
				"implements implicit implicitly implied implies important",
				"impose imposes in inaccessible includes including increase",
				"increased increases indeed independent independently",
				"indicated indication indirection individual information",
				"infrequent inherent initialization initiate initiated input",
				"inquiry insert insertion insertions inside insist inst",
				"instance instances instead instruction instructions insured termtwo termthree",
				"int integer integrated integrating integration intended",
				"intends intent inter interact interaction interactions",
				"interest interesting interface interfaces internal",
				"internetwork interprocess interrogating interrupt interrupts",
				"interval intervals into intolerable intrinsic introduce",
				"introduced introducing introduction invariant invention",
				"invoked invoking involve involved involves iria is",
				"israel issue issues it item iteratively its itself",
				"jan join joining joins jointly july june just",
				"justifies keedy keeping keeps kept key keyboard kind",
				"kinds know known labor lack lackluster laissez",
				"lampson language languages large largely larger last",
				"later latest latter lauer layering lead leads least",
				"leaves leaving lecture left legitimate less let level",
				"levels lexical life like likely likes limited limiting",
				"line lines linked linking list listed lister lists",
				"literature little lo loads local localized locate",
				"location lock locked locks logic logically long longer",
				"looked lost low lower lowest mac machine machinery",
				"machines made main mainframe maintained maintains make",
				"makes making management manager manipulations manner",
				"manual many mapping marking marks match material",
				"maximum may maybury maynard meaning meaningful means",
				"measuring mechanism mechanisms memory mental mesa message termthree",
				"messages met metcalfe method microcode microcoded",
				"microsecond might mild mined minimal minimize minimum",
				"mip missing mit mitchell models moderate modern modest",
				"modula modular modularity module modules monitor monitored",
				"monitorentry monitoring monitors more moreavailable most",
				"motivated moved much multi multiple multiplexed",
				"multiprogramming must mutual mutually naive naked names",
				"nat national natural naturally nearly necessary need",
				"needed needham needs neither nested network networks",
				"never nevertheless new newly next no non none",
				"nonetheless nontrivial nor normal normally not notable",
				"note notes nothing notice noticed notices notification",
				"notified notifies notify nov november now number",
				"numbers object objected objects observed obtained",
				"obtaining occupies occupy occur occurred occurring occurs",
				"ocr oct of offer offered office often ok old on",
				"one only operands operating operation operational",
				"operations opportunities or order ordered ordering orderly",
				"ordinary organizing original other others otherwise our",
				"ours out output outside over overhead own pacific",
				"package packet packets page pages paid pair pairwise",
				"palo paper papers paradigm parallelism parameter",
				"parameters part partial particular particularly parts",
				"pascal pass passed passing path paths pattern patterns",
				"per percent percentage perfectly perform performance",
				"performs periodically permission personal phrases pi pick",
				"UPPERCASEWORD pilot pl place placement plus pn pnew point pointed",
				"pointer pointers pointing pointless points pold policies",
				"poorly popular portion possessed possibilities possibility",
				"possible potential potentially power pp practical practice",
				"precedes precise predicate preempted preemption preemptions",
				"preemptive prentice prepared preparing preplan present",
				"presented press presumably prevent previously primarily",
				"primary prime primitive primitives principles printer",
				"prior priorities priority private problem problems proce",
				"procedure procedures proceed process processed processes",
				"processing processor processors processstate processstates",
				"prod produce producer produces program programmer",
				"programming programs proof proper properly properties",
				"proposal proposals protect protected protection proved",
				"provide provided provides providing provision provisions",
				"prqlwru pseudo public publication published pup purpose",
				"purposes put queue queueing queues quick quite quorum",
				"race races raised random range ranging rapid rapidly",
				"rarely rather reached reacquire reacquired read reader",
				"readline ready real realistic reason reasonable reasonably",
				"reasons rebirth received recent recognizes recommend",
				"recommended record recording records recovery recursive",
				"redell reduces reenters reevaluate reference references",
				"refers refined reflects regard regarded regardless regimes",
				"rejected related relationship relative relatively release",
				"released releases MixedCaseWord releasing reliable remain remains remark",
				"remarkably remote removal rendezvous replacing replenished",
				"replicated reply report reported reports repre",
				"representative representatives represented representing",
				"represents reprinted republish request requesting require",
				"required requirements requires research resemble reserve",
				"reside resident resolve resolved resource resources",
				"respectively respond response responsible restore restored",
				"restoring restricting restriction restrictions restricts",
				"result resultant resulted resulting results resume resumes",
				"retrieve retrieves retry return returned returning returns",
				"review revised right rocquencourt root roughly router",
				"routine routines routing rule rules run runaway running",
				"runs runtime rupt safe safety said saltzer same",
				"san satterthwaite saving saxena say scanning scans",
				"scheduled scheduler scheduling scheme schemes science",
				"scope second secondary section sections see seemed seen",
				"seizing semantics semaphore semaphores send sends",
				"sentatives separate separating september sequence sequential",
				"sequentially serializing serious serve serves serviced set",
				"setting settling several share shared sharing short",
				"should shown signaled signaler signaling signals",
				"significantly sigplan similar simple simpler simplest",
				"simplifies simply simulating simultaneously since single",
				"situation situations size sizes slicing slightly slower",
				"sluggish small so socket software solution solutions",
				"solve solved solves some somehow sometimes somewhat",
				"somewhere soon sorted sound source space special",
				"specific specification specified specify speed speeds terminate",
				"split springer stable stack standard standards start",
				"starvation state statement statements states static status",
				"still stop storage storageallocator store stored",
				"straightforward strategies strict strike strong stronger",
				"structure structured structures structuring sturgis style",
				"subject substantial substantially subtle subverted succeeded",
				"successful such sufficient sufficiently sugar sugared",
				"suggest suicide suitable suite suites sum summarize",
				"summarizes summary supplied supply supplying support",
				"supports suppose surfhvv surgery survey swap swappable",
				"swapping sweet switch switches switching symposium",
				"synchronization synchronize synchronized synchronizers",
				"synchronizes synchronizing syntactic system systems table",
				"tail take taken takes taking tape task techniques",
				"temporarily tend tends terminal",
				"testing tests text textually than that the their",
				"them themselves then there therefore these they think",
				"third this those though thought three through",
				"throughput thus tick ticks tightly time timeout",
				"timeouts times timesharing timing title to together too",
				"tool top total totally tr track traffic trans",
				"transaction transactional transactions transfer transfers",
				"transformation transmission transmit transmitted trap treated",
				"treatment treats tricky tries trouble true truth trying terminates",
				"turn turned turning twice two type types typical",
				"typically typing uhwxuq unable unacceptable unavailable",
				"unbounded unchanged under underlying understand",
				"understandable understanding unfairness unfortunately unifies",
				"unit unless unlocked unnecessary unreasonable unreferenced",
				"unrelated until unused unwind unwinds up update updated",
				"updates updating upheaval upon us usage use used",
				"useful usefulness user users uses using usual usually",
				"utility validity value vanished variable variables variety",
				"various vary varying vector vehicle verification version",
				"very via view views violet virtual volatile volume",
				"voluntarily voluntary voting wait waiter waiters waiting",
				"waits wake wakeup wakeups waking want wanted wants",
				"was way ways we weighted well were what when",
				"whenever where whether which while who whose why",
				"wide will willing wirth wish wishing with within",
				"without word words work worked workshop worst would",
				"write writing written  xerox yet yield yielded"};

}
